### ISSUE TITLE
Don't check #gosec comments

### ISSUE THREAD

**Issue by ernado** [tetafro/godot#1]
Please consider adding `#nosec` as another special case to reduce false-positives.

Example:
```go
// fastXORBytes xors in bulk. It only works on architectures that
// support unaligned read/writes.
//
// #nosec
func fastXORBytes(dst, a, b []byte) int
```

**Comment by tetafro** [comment]
Thanks, I haven't of heard of it. Wonder why they don't use `nolint` tag in gosec.
I'll fix it today.

**Comment by tetafro** [comment]
Fixed. I excluded all hashtag comments from checking.
