### ISSUE TITLE
Strict Mode: Verify all comments.

### ISSUE THREAD

**Issue by bwplotka** [tetafro/godot#11]
Hi :wave: 

This is a little but amazing project. Something we really needed in our project to replace our old mad stuff: https://github.com/thanos-io/thanos/blob/55cb8ca38b3539381dc6a781e637df15c694e50a/scripts/build-check-comments.sh#L85

The only missing bit is that we want to a bit more strict. We actually created bit stricter style guide as well. And as per that https://thanos.io/tip/coding-style-guide.md/#comments-should-be-full-sentences we don't want to allow broken comments (without trailing period, but also not started without a capital letter), anywhere in the code. And the reason is simple: We don't want hacky non-readable comments anywhere. 

Would you consider some PR with a stricter mode that will ensure all comments validated?

cc @kakkoyun

**Comment by tetafro** [comment]
Sounds good. The only problem I see is config - there is already a flag `--all` (for all top-level comments). It would be confusing, if there is another option to check even more (any comment anywhere). I think it would be a right thing to change this behaviour and update package to v2.
If you don't mind I'll do it myself :)

**Comment by tetafro** [comment]
I've added an option to check *all* comments in v1.0.1. It's not in golangci-lint yet, but you can try it with godot cli
```
go get -u github.com/tetafro/godot/cmd/godot
godot --scope all ./myproject
```

**Comment by tetafro** [comment]
Sorry for the delay. Everything is done and is in [golangci-lint now](https://github.com/golangci/golangci-lint/pull/1498).
