### ISSUE TITLE
Excluding API annotations from linting

### ISSUE THREAD

**Issue by kylechadha** [tetafro/godot#14]
Would be great to be able to ignore comments based on a given prefix. For example it does not make much sense to end Swagger API annotations with a dot (example: https://github.com/swaggo/http-swagger#canonical-example), and these all begin with an `@` symbol.

```
// @title Swagger Example API
// @version 1.0
// @description This is a sample server Petstore server.
// @termsOfService http://swagger.io/terms/

// @contact.name API Support
// @contact.url http://www.swagger.io/support
// @contact.email support@swagger.io

// @license.name Apache 2.0
// @license.url http://www.apache.org/licenses/LICENSE-2.0.html

// @host petstore.swagger.io
// @BasePath /v2
func main() {
	r := chi.NewRouter()

	r.Get("/swagger/*", httpSwagger.Handler(
		httpSwagger.URL("http://localhost:1323/swagger/doc.json"), //The url pointing to API definition"
	))

	http.ListenAndServe(":1323", r)
}
```

**Comment by tetafro** [comment]
Great idea, thanks. I'll do it.

**Comment by tetafro** [comment]
It's now in master in golangci-lint. And also in godot cli since v1.4.4.

https://github.com/golangci/golangci-lint/blob/master/.golangci.example.yml#L197

**Comment by kylechadha** [comment]
Amazing, thank you!

**Comment by tetafro** [comment]
That's right, `@`-prefixed lines are not excluded by default, you need to use regexp for it.
