### ISSUE TITLE
Document the name of the config file?

### ISSUE THREAD

**Issue by jeffwidman** [tetafro/godot#16]
The `README` references a config file, but nowhere is the name of the file documented... ie, what name do I need to give the file to make it get picked up by `godot`?

**Comment by jeffwidman** [comment]
It looks like the name of the file is `config.yaml`: https://github.com/tetafro/godot/blob/5996335183e6f3ece2b8c0bc32c4b4c81c541d78/cmd/godot/main.go#L20

Can this be changed? `config.yml` is super generic, it'd be better to name this something like `.godot.yaml`...

**Comment by tetafro** [comment]
> `.godot.yaml`

Sounds good

> I'm happy to open a PR

Yes, please.

**Comment by tetafro** [comment]
Fixed in [1.4.6](https://github.com/tetafro/godot/releases/tag/v1.4.6)
