### ISSUE TITLE
Support passing in config via the CLI perhaps a JSON/YAML dict?

### ISSUE THREAD

**Issue by jeffwidman** [tetafro/godot#17]
It'd be helpful to be able to pass in config via a YAML or JSON dict on the CLI... See how `yamllint` does it. 

This way we don't need yet another config file if we only want to tweak one setting in `godot`.

**Comment by tetafro** [comment]
There are CLI arguments that can be used instead of config file. See `godot -h`.

But why don't you just use golangci-lint? I actually thought nobody uses separate linters, only as a part of golangci.
