### ISSUE TITLE
Add sentence ending chars for East Asian area

### ISSUE THREAD

**Issue by KEINOS** [tetafro/godot#24]
First of all, thank you for providing us such a useful tool!

I'm using `godot` via `golangci-lint` very much. And I would like to have the below Asian sentence ending chars in the `lastChars` list:

- `。` (U+3002)
-  `！` (U+FF09)
- `）` (U+FF01)
- `？` (U+FF1F)

Which are mostly used in China, Korea, and Japan. (a.k.a. CJK characters)

I tried to exclude them in the config but it seems not working in the below way.

```YAML
scope: all
exclude:
  - "[。）！]$"
period: true
capital: false
```

The preferred way is to implement a `setter` method to `godot` but the easiest way may be to add the chars to the `lastChars` slice like so:

https://github.com/tetafro/godot/blob/1fc98824bc49256904e996ee96f0c9e457776621/checks.go#L19

```diff
-	lastChars = []string{".", "?", "!", ".)", "?)", "!)", specialReplacer}
+	lastChars = []string{".", "?", "!", ".)", "?)", "!)", "。", "？", "！", "。）", "？）", "！）", specialReplacer}
```

Or, is there another alternative way to let them pass without changing the `godot`s code?

**Comment by tetafro** [comment]
> Asian sentence ending chars

Interesting, I haven't heard about it :)

> but the easiest way may be to add the chars to the lastChars

Yeah, I think it is the easiest way. You can send a PR, or I'll fix it tomorrow by myself.

**Comment by tetafro** [comment]
Done - [v1.4.9](https://github.com/tetafro/godot/releases/tag/v1.4.9)
