### ISSUE TITLE
always add dot after code block in comment

### ISSUE THREAD

**Issue by daixiang0** [tetafro/godot#25]
```
// xxx
/* func test {
}
*/
```

It always add dot after `}`, I try to add "}" to skip but fail.

The case refers to https://github.com/dapr/components-contrib/pull/1102#pullrequestreview-745522769.

**Comment by tetafro** [comment]
Hey. This config option works for me:
```yaml
exclude:
  - '}'
```

But there was another bug, which this issue revealed :) So first update to v1.4.11.
