### ISSUE TITLE
cgo export comment should not fail

### ISSUE THREAD

**Issue by sni** [tetafro/godot#3]
When using cgo, exported functions must not end with a dot, so they should be excluded here:

```
main.go:40:1: Top level comment should end in a period (godot)
//export cgo_exported_function_name
```

see https://golang.org/cmd/cgo/#hdr-C_references_to_Go

**Comment by tetafro** [comment]
You're right, thanks.
I fixed in v0.3.7. Will submit PR to golangci-lint soon.
