### ISSUE TITLE
BUG: golang version

### ISSUE THREAD

**Issue by kehiy** [tetafro/godot#30]
the godot is not synced with the new Golang version and syntax I think!

I have this struct :
```go
type store struct {
	lk sync.RWMutex

	config         *Config
	db             *leveldb.DB
	batch          *leveldb.Batch
	blockStore     *blockStore
	txStore        *txStore
	accountStore   *accountStore
	validatorStore *validatorStore
	stampLookup    *linkedmap.LinkedMap[hash.Stamp, blockHeightPair]
}
```

and the `stampLookup` syntax is ok!

but when I'm running: `godot -w ./`

I get this: `Failed to parse file './': store/store.go:65:37: expected ';', found '[' (and 2 more errors)`

**Comment by tetafro** [comment]
You can check it now, I updated it to 1.21.

**Comment by ldez** [comment]
Generics have been introduced in go1.18 so you don't need to use go1.21, you can use a lower version (go1.20). Related to #31

**Comment by kehiy** [comment]
@tetafro thank you, I will update and check it.
