### ISSUE TITLE
module go version

### ISSUE THREAD

**Issue by ldez** [tetafro/godot#31]
It's possible for you to downgrade the version inside your go.mod to go1.20?

the new way to handle the module and go version is strict.

https://github.com/golangci/golangci-lint/actions/runs/5899819942/job/16002953607?pr=4025

https://go.dev/blog/toolchain

https://github.com/golangci/golangci-lint/pull/4025

**Comment by tetafro** [comment]
Oh, didn't know that. Thanks for sharing. I downgraded to 1.20.
