### ISSUE TITLE
Bash script to fix everything.

### ISSUE THREAD

**Issue by boolooper** [tetafro/godot#6]
From [https://gist.github.com/boolooper/e7b82efbea767629078fd54aa569642f](https://gist.github.com/boolooper/e7b82efbea767629078fd54aa569642f)

```
#!/bin/bash
fix(){
    linenum=${1#*":"}
    filename=./${1%":"*}
    sed -i '' "${linenum}s=$=.=" $filename
}

godot ./ | grep '.go' | cut -c 42- | rev | cut -c 3- | rev | while read x; do fix $x; done
```

This can fix all the errors. However, I am expecting that `godot` should have a flag like that `godot -fix -diff` or `godot -fix -write` to fix every report. Or include this bash script to README. because fixing every old comment without a `.` is boring as hell. sigh! 😔

**Comment by mcristina422** [comment]
This could be added to GolangCI Lint with the `--fix` mode

**Comment by boolooper** [comment]
Yeah! That's also a good option.

**Comment by tetafro** [comment]
> This could be added to GolangCI Lint with the --fix mode

Yeah, I was going to do this as soon as I have free time

**Comment by tetafro** [comment]
I've added autofix the last release (see updated readme).

Will add this to golangci-lint a bit later.

**Comment by tetafro** [comment]
Done: https://github.com/golangci/golangci-lint/pull/1150
