### ISSUE TITLE
Don't match Kubernetes generator tags

### ISSUE THREAD

**Issue by twelho** [tetafro/godot#9]
The Kubernetes project has [code generators](https://github.com/kubernetes/code-generator) to automatically generate boilerplate code for structs. The generators read tags in the form of `// +org:generator[:parameter]=value`, similar to the `// +build` tags of Go. The space between the `//` and the `+` is a common convention, but not a requirement.

Package-level generator configurations are commonly a "top-level comment":
```go
$ cat doc.go
// +k8s:deepcopy-gen=package
// +k8s:defaulter-gen=TypeMeta
// +k8s:conversion-gen=github.com/project/package
package v1alpha1
```

These tags can also be defined for individual structs:
```go
// The tags can also be "inline" (attached to structs somewhere in the code) 
// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object
type MyObject struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
}
```

godot incorrectly matches these generator tags as lacking a period:

```
$ ./godot -f . | grep "+k8s"
// +k8s:deepcopy-gen=package
// +k8s:defaulter-gen=TypeMeta
// +k8s:conversion-gen=github.com/project/package
// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object.
//+k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object.
```
```
$ ./godot -a -f . | grep "+k8s"
// +k8s:deepcopy-gen=package
// +k8s:defaulter-gen=TypeMeta
// +k8s:conversion-gen=github.com/project/package.
// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object.
//+k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object.
```

Could there be an exclusion added for these tags (comment lines starting with a `+`)?

**Comment by tetafro** [comment]
I've added exclusion for `^\+?[a-z0-9]+:` in v0.4.7. It will work for your examples.
New version will appear in golangci-lint in a few days.

**Comment by twelho** [comment]
Great, thank you! :clap:
